# Generated by Django 2.2.1 on 2019-05-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='img/blog')),
                ('author', models.CharField(max_length=150)),
                ('blog_time', models.DateTimeField()),
                ('blog_article', models.TextField(blank=True)),
                ('article_highlight', models.TextField(blank=True)),
            ],
        ),
    ]
