# Generated by Django 2.2.1 on 2019-05-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_headline',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
