# Generated by Django 2.2.1 on 2019-05-14 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlisting',
            name='image',
            field=models.ImageField(upload_to='img/feature'),
        ),
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 18, 9, 34, 485982)),
        ),
    ]
