# Generated by Django 2.2.1 on 2019-05-14 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0002_auto_20190514_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredlisting',
            name='street_number',
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='bathrooms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 18, 13, 15, 809992)),
        ),
    ]
