# Generated by Django 2.2.1 on 2019-05-14 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0003_auto_20190514_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 18, 14, 35, 111272)),
        ),
    ]
