# Generated by Django 2.2.1 on 2019-05-14 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0004_auto_20190514_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredlisting',
            old_name='bathrooms',
            new_name='bathroom',
        ),
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 18, 15, 16, 394698)),
        ),
    ]
