# Generated by Django 2.2.1 on 2019-05-14 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0005_auto_20190514_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredlisting',
            old_name='rent_or_sale',
            new_name='sale_rent',
        ),
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 18, 22, 44, 420493)),
        ),
    ]
