# Generated by Django 2.2.1 on 2019-05-14 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0006_auto_20190514_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 18, 25, 15, 419395)),
        ),
    ]
