# Generated by Django 2.2.1 on 2019-05-15 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0007_auto_20190514_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredlisting',
            name='air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='build_age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='building_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='central_heating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='city_views',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='electric_range',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='image1',
            field=models.ImageField(null=True, upload_to='img/feature/detail'),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='image2',
            field=models.ImageField(null=True, upload_to='img/feature/detail'),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='image3',
            field=models.ImageField(null=True, upload_to='img/feature/detail'),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='image4',
            field=models.ImageField(null=True, upload_to='img/feature/detail'),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='internet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='laundry_room',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='metro_central',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='telephone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 7, 55, 57, 423828)),
        ),
    ]
