# Generated by Django 2.2.1 on 2019-05-15 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0008_auto_20190515_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 13, 13, 12, 153359)),
        ),
    ]
