# Generated by Django 2.2.1 on 2019-05-16 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0015_auto_20190515_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 17, 6, 23, 849664)),
        ),
    ]
