# Generated by Django 2.2.1 on 2019-05-19 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_listing', '0016_auto_20190516_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlisting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 10, 53, 51, 295521)),
        ),
    ]
