# Generated by Django 2.2.1 on 2019-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(upload_to='img/about')),
            ],
        ),
    ]
